blend_path: ${oc.env:PWD}/src/nemotron/recipes/nano3/stage1_sft/config/data_blend_tiny.json
output_dir: ${oc.env:PWD}/../output/stage1_sft_tiny
tokenizer_model: nvidia/NVIDIA-Nemotron-Nano-9B-v2
pack_size: 4096
shard_size: 64MB
train_ratio: 0.98
valid_ratio: 0.01
test_ratio: 0.01
chat_template: nano3
messages_field: messages
tools_field: tools
used_in_filter: nano_v3
used_in_field: used_in
max_doc_tokens: null
sample: 1000
num_actors: null
force: false
